[package]
name = "svelte-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
logos = "0.12"

[profile.release]
lto = true
codegen-units = 1
opt-level = 3
panic = "abort"
strip = true
